/**
 * exercises.js
 * All exercise definitions — metadata, cues, guide steps, and analysis function references.
 * To add a new exercise: add an entry here and create its analyzer in pose-analyzer.js
 */

window.EXERCISES = [
  {
    id: "plank",
    name: "Plank",
    icon: "🏋️",
    difficulty: "medium",
    muscle: "Core & Shoulders",
    guide: [
      "Start face-down, forearms flat on the floor",
      "Elbows directly under your shoulders",
      "Rise onto your toes — body forms a dead-straight line",
      "Squeeze your abs like you're about to take a punch",
      "Hold the position — don't hold your breath",
    ],
    cues: {
      hips_low:  "Hips are dropping — squeeze your glutes and pull them up.",
      hips_high: "Hips are too high — lower them into a straight line.",
      head_up:   "Head down — eyes on the floor, not forward.",
      good:      "Solid plank. Stay tight and breathe steady.",
    },
    analyzerKey: "plank",
  },
  {
    id: "squat",
    name: "Squat",
    icon: "🦵",
    difficulty: "easy",
    muscle: "Quads, Glutes & Hamstrings",
    guide: [
      "Feet shoulder-width apart, toes angled slightly out",
      "Brace your core before you move",
      "Sit back and down — chest stays tall",
      "Push your knees out in line with your toes",
      "Drive through your heels to stand back up",
    ],
    cues: {
      depth:     "Go deeper — get your thighs parallel to the ground.",
      knee_cave: "Push your knees out — don't let them collapse in.",
      chest:     "Chest up — don't lean forward, stay tall.",
      good:      "Nice squat. Hit that depth and drive back up.",
    },
    analyzerKey: "squat",
  },
  {
    id: "push-up",
    name: "Push-Up",
    icon: "💪",
    difficulty: "medium",
    muscle: "Chest, Triceps & Core",
    guide: [
      "Hands just wider than shoulder-width",
      "Full arm extension to start — body straight",
      "Lower until your chest nearly touches the floor",
      "Elbows at 45 degrees — not flared straight out",
      "Press back up to full extension",
    ],
    cues: {
      hips:    "Keep your body straight — core is sagging.",
      elbows:  "Tuck your elbows — 45 degrees, not flared wide.",
      depth:   "Go all the way down — chest to the floor.",
      good:    "Perfect push-up. Full range, body straight.",
    },
    analyzerKey: "pushup",
  },
  {
    id: "lunge",
    name: "Lunge",
    icon: "🏃",
    difficulty: "easy",
    muscle: "Quads, Glutes & Balance",
    guide: [
      "Stand tall, feet together",
      "Step forward far enough that front knee stays over ankle",
      "Lower your back knee toward the floor",
      "Front thigh parallel to ground at the bottom",
      "Push through the front heel to return",
    ],
    cues: {
      knee_over:  "Knee is too far forward — step wider.",
      torso_lean: "Torso is leaning — keep your back straight.",
      depth:      "Lower your back knee closer to the floor.",
      good:       "Clean lunge. Good depth, torso upright.",
    },
    analyzerKey: "lunge",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    icon: "🏋️‍♂️",
    difficulty: "hard",
    muscle: "Posterior Chain & Core",
    guide: [
      "Feet hip-width apart, bar over mid-foot",
      "Hinge at the hips — don't squat down to it",
      "Neutral spine: chest proud, no rounding",
      "Engage your lats before you pull",
      "Drive through the floor to stand — lock hips and knees together",
    ],
    cues: {
      round_back: "Stop rounding your back — chest up, neutral spine.",
      hips_high:  "Don't shoot your hips up — keep your chest and hips rising together.",
      head:       "Neutral neck — don't crane your head up.",
      good:       "Strong pull. Spine neutral, full lockout.",
    },
    analyzerKey: "deadlift",
  },
  {
    id: "shoulder-press",
    name: "Shoulder Press",
    icon: "🤸",
    difficulty: "medium",
    muscle: "Deltoids & Triceps",
    guide: [
      "Weights at shoulder height, elbows in front of body",
      "Feet shoulder-width, core braced",
      "Press directly overhead — fully extend arms",
      "Don't arch your lower back during the press",
      "Lower back to shoulders with full control",
    ],
    cues: {
      arch:       "Stop arching your back — brace that core tight.",
      lockout:    "Fully extend — press all the way to the top.",
      head:       "Don't jut your head forward — keep it neutral.",
      good:       "Clean press. Full extension, core tight.",
    },
    analyzerKey: "shoulderpress",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    icon: "🍑",
    difficulty: "easy",
    muscle: "Glutes & Hamstrings",
    guide: [
      "Lie on your back, knees bent, feet flat",
      "Feet hip-width apart, close to your glutes",
      "Drive through your heels to push hips up",
      "Squeeze your glutes hard at the top",
      "Hold for a second, then lower with control",
    ],
    cues: {
      height:   "Drive your hips higher — squeeze those glutes.",
      squeeze:  "Squeeze at the top — hold it for a full second.",
      feet:     "Keep your feet flat and push through your heels.",
      good:     "Great bridge. Full extension, glutes firing.",
    },
    analyzerKey: "glutebridge",
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    icon: "🧗",
    difficulty: "medium",
    muscle: "Core, Cardio & Hip Flexors",
    guide: [
      "Start in a high push-up position",
      "Hands directly under shoulders",
      "Drive one knee toward your chest",
      "Alternate quickly — keep your hips low",
      "Maintain a rigid plank through every rep",
    ],
    cues: {
      hips_up:   "Hips are rising — keep your core flat and tight.",
      slow:      "Drive the knees in faster — pump those legs.",
      good:      "Good pace. Hips low, core locked in.",
    },
    analyzerKey: "mountainclimber",
  },
  {
    id: "jumping-jack",
    name: "Jumping Jack",
    icon: "⭐",
    difficulty: "easy",
    muscle: "Full Body Cardio",
    guide: [
      "Start with feet together, arms at sides",
      "Jump feet out to shoulder-width while raising arms overhead",
      "Land softly on the balls of your feet",
      "Jump back in and repeat",
      "Keep a steady rhythm — don't rush",
    ],
    cues: {
      arms:  "Raise your arms fully — all the way overhead.",
      land:  "Soften your landing — land on the balls of your feet.",
      good:  "Good rhythm. Arms full extension every rep.",
    },
    analyzerKey: "jumpingjack",
  },
  {
    id: "burpee",
    name: "Burpee",
    icon: "🔥",
    difficulty: "hard",
    muscle: "Full Body Power",
    guide: [
      "Stand with feet shoulder-width apart",
      "Drop to a squat and place hands on the floor",
      "Jump feet back into a high push-up position",
      "Do one push-up — chest to the floor",
      "Jump feet back to hands, then jump up with arms overhead",
    ],
    cues: {
      hips:    "Lock your hips — don't let them sag in the plank.",
      jump:    "Jump higher — full extension at the top.",
      pushup:  "Get that chest to the floor on the push-up.",
      good:    "Full burpee. Stay explosive and keep moving.",
    },
    analyzerKey: "burpee",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    icon: "🦅",
    difficulty: "medium",
    muscle: "Lateral Deltoids",
    guide: [
      "Stand tall, weights at your sides",
      "Slight bend in the elbows throughout",
      "Raise arms out to the sides to shoulder height",
      "Lead with your elbows — not your hands",
      "Lower with control — don't just drop them",
    ],
    cues: {
      height:   "Raise to shoulder height — don't stop short.",
      swing:    "Stop swinging — slow it down and control the lift.",
      elbows:   "Lead with your elbows, not your wrists.",
      good:     "Clean raises. Controlled and hitting shoulder height.",
    },
    analyzerKey: "lateralraise",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    icon: "🚴",
    difficulty: "medium",
    muscle: "Obliques & Core",
    guide: [
      "Lie on your back, hands lightly behind your head",
      "Lift both shoulders off the ground",
      "Drive one knee to your chest while extending the other",
      "Rotate your torso — elbow toward opposite knee",
      "Alternate sides in a slow, controlled rhythm",
    ],
    cues: {
      neck:    "Don't pull your neck — hands are for support only.",
      range:   "Extend that leg fully — full range of motion.",
      slow:    "Slow it down — control beats speed here.",
      good:    "Good rotation. Shoulders up, full extension.",
    },
    analyzerKey: "bicyclecrunch",
  },
];
